Setup ActivityPreset and UserActivity
sopra-fs21-group-16/mth-server pull request #47
Opened 2021-04-03 13:25 UTC by AleksandarRistic99

#18 #21

2021-04-03 13:25 UTC, AleksandarRistic99 commented
Also added support classes and Repositories.

-Made UserStatus for activity --> UserDecisionStatus (mentioned in presentation to change the name)

-Made UserDecisionStatus to be an entity in a table, otherwise no relationship between UserDecisionStatus and UserActivity was possible (maybe there is another solution to enable relationship but dont store UserDecisionStatus as a entity in a table ?)

2021-04-03 14:36 UTC, SamuelBruegger approved these changes
- ih de class UserDecisionStatus chönt meh sich öberlege de DecisionStatus zum ne enum z mache anstatt boolean, falls meh jemols wet funktione, wie superlike oder so ihbaue abr da isch halt eifach eh design frog, wo meh au spöter glaubs guet chöntet ändere

2021-04-03 16:10 UTC, AleksandarRistic99 commented
> * ih de class UserDecisionStatus chönt meh sich öberlege de DecisionStatus zum ne enum z mache anstatt boolean, falls meh jemols wet funktione, wie superlike oder so ihbaue abr da isch halt eifach eh design frog, wo meh au spöter glaubs guet chöntet ändere

Guete punkt, chame denn sicher no in zuekunft beachte, eventuell en enum mache wo TRUE, FALSE, und no wiiteri optione het wie SUPERLIKE

2021-04-03 16:17 UTC, AleksandarRistic99 commented
Han de vorschlag vom Samuel mal apasst, ich denk es schadet sicher ned wenn mer de code extendable halte

2021-04-04 20:33 UTC, Taremeh commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entities/ActivityPreset.java
> +     */
```suggestion
     private GooglePOI googlePOI;
```

I'd say that's alright. The GooglePOI object only contains minimal information for the API request (e.g. 'keyword = sushi' for an activity _eat at sushi restaurant_). There is no location saved in `GooglePOI`.

2021-04-04 20:34 UTC, Taremeh commented on src/main/java/ch/uzh/ifi/hase/soprafs21/entities/ActivityPreset.java
> +     private GooglePOI googlePOI;
```suggestion
    private GooglePOI googlePOI;
```

2021-04-04 20:47 UTC, Taremeh requested changes
- Good point regarding the `DecisionStatus`.
However, I would rename it to `SwipeStatus` since it's not directly clear what's meant by decision status. `SwipeStatus` would be clearer, also regarding SuperLike. 

- To simplify naming, I'd also suggest to call activities just `Activity` instead of `UserActivity`. (user activity sounds as if the user has created the activity which is not true)

- Regarding `GooglePOI`: that's all fine (see commit). Please implement the Spring Annotation and getters & setters. 

And btw. thx for deleting the outdated imports 🙏

2021-04-05 07:58 UTC, merged

2021-04-05 10:13 UTC, Taremeh commented
⚠️  Still missing getters & setters for GooglePOI (https://github.com/sopra-fs21-group-16/mth-server/pull/47#discussion_r606850667)